################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../gmp_src_mgr/gmp_src/PCA9555.c \
../gmp_src_mgr/gmp_src/crc16.c \
../gmp_src_mgr/gmp_src/ctl_adv_back_stepping.c \
../gmp_src_mgr/gmp_src/ctl_adv_flc.c \
../gmp_src_mgr/gmp_src/ctl_adv_flpid.c \
../gmp_src_mgr/gmp_src/ctl_adv_ilc.c \
../gmp_src_mgr/gmp_src/ctl_adv_imc.c \
../gmp_src_mgr/gmp_src/ctl_adv_lms.c \
../gmp_src_mgr/gmp_src/ctl_adv_lut_pair.c \
../gmp_src_mgr/gmp_src/ctl_adv_mrac.c \
../gmp_src_mgr/gmp_src/ctl_adv_rc.c \
../gmp_src_mgr/gmp_src/ctl_adv_sinc_interpolator.c \
../gmp_src_mgr/gmp_src/ctl_adv_smc.c \
../gmp_src_mgr/gmp_src/ctl_adv_surf_search.c \
../gmp_src_mgr/gmp_src/ctl_cia402_callback_fn.c \
../gmp_src_mgr/gmp_src/ctl_cia402_state_machine.c \
../gmp_src_mgr/gmp_src/ctl_component_interface.c \
../gmp_src_mgr/gmp_src/ctl_continuous_pi.c \
../gmp_src_mgr/gmp_src/ctl_continuous_pid.c \
../gmp_src_mgr/gmp_src/ctl_continuous_pid_aw.c \
../gmp_src_mgr/gmp_src/ctl_discrete_biquad_filter.c \
../gmp_src_mgr/gmp_src/ctl_discrete_df.c \
../gmp_src_mgr/gmp_src/ctl_discrete_filter.c \
../gmp_src_mgr/gmp_src/ctl_discrete_lead_lag.c \
../gmp_src_mgr/gmp_src/ctl_discrete_pid.c \
../gmp_src_mgr/gmp_src/ctl_discrete_pole_zero.c \
../gmp_src_mgr/gmp_src/ctl_discrete_pr.c \
../gmp_src_mgr/gmp_src/ctl_discrete_sg.c \
../gmp_src_mgr/gmp_src/ctl_discrete_sogi.c \
../gmp_src_mgr/gmp_src/ctl_discrete_track_pid.c \
../gmp_src_mgr/gmp_src/ctl_disrete_fir.c \
../gmp_src_mgr/gmp_src/ctl_divider.c \
../gmp_src_mgr/gmp_src/ctl_dp_basic.c \
../gmp_src_mgr/gmp_src/ctl_hysteresis_controller.c \
../gmp_src_mgr/gmp_src/ctl_if_pwm_h.c \
../gmp_src_mgr/gmp_src/ctl_if_pwm_npc.c \
../gmp_src_mgr/gmp_src/ctl_if_pwm_spwm.c \
../gmp_src_mgr/gmp_src/ctl_internal_ladrc1.c \
../gmp_src_mgr/gmp_src/ctl_internal_ladrc2.c \
../gmp_src_mgr/gmp_src/ctl_itoc_protection.c \
../gmp_src_mgr/gmp_src/ctl_mc_acim_consultant.c \
../gmp_src_mgr/gmp_src/ctl_mc_acim_fo.c \
../gmp_src_mgr/gmp_src/ctl_mc_acim_pos_calc.c \
../gmp_src_mgr/gmp_src/ctl_mc_acim_smo.c \
../gmp_src_mgr/gmp_src/ctl_mc_ato_pll.c \
../gmp_src_mgr/gmp_src/ctl_mc_basic_mech_ctrl.c \
../gmp_src_mgr/gmp_src/ctl_mc_bldc_hall.c \
../gmp_src_mgr/gmp_src/ctl_mc_bldc_zcd_obs.c \
../gmp_src_mgr/gmp_src/ctl_mc_dtc_svm_core.c \
../gmp_src_mgr/gmp_src/ctl_mc_encoder.c \
../gmp_src_mgr/gmp_src/ctl_mc_encoder_switcher.c \
../gmp_src_mgr/gmp_src/ctl_mc_foc_core.c \
../gmp_src_mgr/gmp_src/ctl_mc_imfoc_core.c \
../gmp_src_mgr/gmp_src/ctl_mc_inverter_consultant.c \
../gmp_src_mgr/gmp_src/ctl_mc_ipm_fw.c \
../gmp_src_mgr/gmp_src/ctl_mc_ladrc_pos_ctrl.c \
../gmp_src_mgr/gmp_src/ctl_mc_ladrc_spd_ctrl.c \
../gmp_src_mgr/gmp_src/ctl_mc_lut_fw.c \
../gmp_src_mgr/gmp_src/ctl_mc_mech_consultant.c \
../gmp_src_mgr/gmp_src/ctl_mc_mit_mech_ctrl.c \
../gmp_src_mgr/gmp_src/ctl_mc_mtr_protection.c \
../gmp_src_mgr/gmp_src/ctl_mc_mtr_vf_generator.c \
../gmp_src_mgr/gmp_src/ctl_mc_nameplate_consultant.c \
../gmp_src_mgr/gmp_src/ctl_mc_pmsm_consultant.c \
../gmp_src_mgr/gmp_src/ctl_mc_pmsm_dbptc.c \
../gmp_src_mgr/gmp_src/ctl_mc_pmsm_esmo.c \
../gmp_src_mgr/gmp_src/ctl_mc_pmsm_fo.c \
../gmp_src_mgr/gmp_src/ctl_mc_pmsm_hfi.c \
../gmp_src_mgr/gmp_src/ctl_mc_pu_consultant.c \
../gmp_src_mgr/gmp_src/ctl_mc_s_curve_traj.c \
../gmp_src_mgr/gmp_src/ctl_mc_smc_mech_ctrl.c \
../gmp_src_mgr/gmp_src/ctl_mc_sogi_traj.c \
../gmp_src_mgr/gmp_src/ctl_mc_spm_fw.c \
../gmp_src_mgr/gmp_src/ctl_mc_trapezoudal_traj.c \
../gmp_src_mgr/gmp_src/ctl_nano.c \
../gmp_src_mgr/gmp_src/ctl_protection.c \
../gmp_src_mgr/gmp_src/ctl_sag_swell.c \
../gmp_src_mgr/gmp_src/ctl_saturation.c \
../gmp_src_mgr/gmp_src/ctl_slope_limiter.c \
../gmp_src_mgr/gmp_src/ctl_sogi.c \
../gmp_src_mgr/gmp_src/ctl_track_pid.c \
../gmp_src_mgr/gmp_src/gmp_at_device.c \
../gmp_src_mgr/gmp_src/gmp_datalink.c \
../gmp_src_mgr/gmp_src/gmp_dev_util.c \
../gmp_src_mgr/gmp_src/gmp_mem_presp.c \
../gmp_src_mgr/gmp_src/gmp_mm_block_memory.c \
../gmp_src_mgr/gmp_src/gmp_pil_core.c \
../gmp_src_mgr/gmp_src/gmp_process_mgr.c \
../gmp_src_mgr/gmp_src/gmp_std_error_code.c \
../gmp_src_mgr/gmp_src/gmp_std_port.c \
../gmp_src_mgr/gmp_src/gmp_tunable.c \
../gmp_src_mgr/gmp_src/ht16k33.c \
../gmp_src_mgr/gmp_src/peripheral_driver.c \
../gmp_src_mgr/gmp_src/sysconfig_adapter.c 

C_DEPS += \
./gmp_src_mgr/gmp_src/PCA9555.d \
./gmp_src_mgr/gmp_src/crc16.d \
./gmp_src_mgr/gmp_src/ctl_adv_back_stepping.d \
./gmp_src_mgr/gmp_src/ctl_adv_flc.d \
./gmp_src_mgr/gmp_src/ctl_adv_flpid.d \
./gmp_src_mgr/gmp_src/ctl_adv_ilc.d \
./gmp_src_mgr/gmp_src/ctl_adv_imc.d \
./gmp_src_mgr/gmp_src/ctl_adv_lms.d \
./gmp_src_mgr/gmp_src/ctl_adv_lut_pair.d \
./gmp_src_mgr/gmp_src/ctl_adv_mrac.d \
./gmp_src_mgr/gmp_src/ctl_adv_rc.d \
./gmp_src_mgr/gmp_src/ctl_adv_sinc_interpolator.d \
./gmp_src_mgr/gmp_src/ctl_adv_smc.d \
./gmp_src_mgr/gmp_src/ctl_adv_surf_search.d \
./gmp_src_mgr/gmp_src/ctl_cia402_callback_fn.d \
./gmp_src_mgr/gmp_src/ctl_cia402_state_machine.d \
./gmp_src_mgr/gmp_src/ctl_component_interface.d \
./gmp_src_mgr/gmp_src/ctl_continuous_pi.d \
./gmp_src_mgr/gmp_src/ctl_continuous_pid.d \
./gmp_src_mgr/gmp_src/ctl_continuous_pid_aw.d \
./gmp_src_mgr/gmp_src/ctl_discrete_biquad_filter.d \
./gmp_src_mgr/gmp_src/ctl_discrete_df.d \
./gmp_src_mgr/gmp_src/ctl_discrete_filter.d \
./gmp_src_mgr/gmp_src/ctl_discrete_lead_lag.d \
./gmp_src_mgr/gmp_src/ctl_discrete_pid.d \
./gmp_src_mgr/gmp_src/ctl_discrete_pole_zero.d \
./gmp_src_mgr/gmp_src/ctl_discrete_pr.d \
./gmp_src_mgr/gmp_src/ctl_discrete_sg.d \
./gmp_src_mgr/gmp_src/ctl_discrete_sogi.d \
./gmp_src_mgr/gmp_src/ctl_discrete_track_pid.d \
./gmp_src_mgr/gmp_src/ctl_disrete_fir.d \
./gmp_src_mgr/gmp_src/ctl_divider.d \
./gmp_src_mgr/gmp_src/ctl_dp_basic.d \
./gmp_src_mgr/gmp_src/ctl_hysteresis_controller.d \
./gmp_src_mgr/gmp_src/ctl_if_pwm_h.d \
./gmp_src_mgr/gmp_src/ctl_if_pwm_npc.d \
./gmp_src_mgr/gmp_src/ctl_if_pwm_spwm.d \
./gmp_src_mgr/gmp_src/ctl_internal_ladrc1.d \
./gmp_src_mgr/gmp_src/ctl_internal_ladrc2.d \
./gmp_src_mgr/gmp_src/ctl_itoc_protection.d \
./gmp_src_mgr/gmp_src/ctl_mc_acim_consultant.d \
./gmp_src_mgr/gmp_src/ctl_mc_acim_fo.d \
./gmp_src_mgr/gmp_src/ctl_mc_acim_pos_calc.d \
./gmp_src_mgr/gmp_src/ctl_mc_acim_smo.d \
./gmp_src_mgr/gmp_src/ctl_mc_ato_pll.d \
./gmp_src_mgr/gmp_src/ctl_mc_basic_mech_ctrl.d \
./gmp_src_mgr/gmp_src/ctl_mc_bldc_hall.d \
./gmp_src_mgr/gmp_src/ctl_mc_bldc_zcd_obs.d \
./gmp_src_mgr/gmp_src/ctl_mc_dtc_svm_core.d \
./gmp_src_mgr/gmp_src/ctl_mc_encoder.d \
./gmp_src_mgr/gmp_src/ctl_mc_encoder_switcher.d \
./gmp_src_mgr/gmp_src/ctl_mc_foc_core.d \
./gmp_src_mgr/gmp_src/ctl_mc_imfoc_core.d \
./gmp_src_mgr/gmp_src/ctl_mc_inverter_consultant.d \
./gmp_src_mgr/gmp_src/ctl_mc_ipm_fw.d \
./gmp_src_mgr/gmp_src/ctl_mc_ladrc_pos_ctrl.d \
./gmp_src_mgr/gmp_src/ctl_mc_ladrc_spd_ctrl.d \
./gmp_src_mgr/gmp_src/ctl_mc_lut_fw.d \
./gmp_src_mgr/gmp_src/ctl_mc_mech_consultant.d \
./gmp_src_mgr/gmp_src/ctl_mc_mit_mech_ctrl.d \
./gmp_src_mgr/gmp_src/ctl_mc_mtr_protection.d \
./gmp_src_mgr/gmp_src/ctl_mc_mtr_vf_generator.d \
./gmp_src_mgr/gmp_src/ctl_mc_nameplate_consultant.d \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_consultant.d \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_dbptc.d \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_esmo.d \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_fo.d \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_hfi.d \
./gmp_src_mgr/gmp_src/ctl_mc_pu_consultant.d \
./gmp_src_mgr/gmp_src/ctl_mc_s_curve_traj.d \
./gmp_src_mgr/gmp_src/ctl_mc_smc_mech_ctrl.d \
./gmp_src_mgr/gmp_src/ctl_mc_sogi_traj.d \
./gmp_src_mgr/gmp_src/ctl_mc_spm_fw.d \
./gmp_src_mgr/gmp_src/ctl_mc_trapezoudal_traj.d \
./gmp_src_mgr/gmp_src/ctl_nano.d \
./gmp_src_mgr/gmp_src/ctl_protection.d \
./gmp_src_mgr/gmp_src/ctl_sag_swell.d \
./gmp_src_mgr/gmp_src/ctl_saturation.d \
./gmp_src_mgr/gmp_src/ctl_slope_limiter.d \
./gmp_src_mgr/gmp_src/ctl_sogi.d \
./gmp_src_mgr/gmp_src/ctl_track_pid.d \
./gmp_src_mgr/gmp_src/gmp_at_device.d \
./gmp_src_mgr/gmp_src/gmp_datalink.d \
./gmp_src_mgr/gmp_src/gmp_dev_util.d \
./gmp_src_mgr/gmp_src/gmp_mem_presp.d \
./gmp_src_mgr/gmp_src/gmp_mm_block_memory.d \
./gmp_src_mgr/gmp_src/gmp_pil_core.d \
./gmp_src_mgr/gmp_src/gmp_process_mgr.d \
./gmp_src_mgr/gmp_src/gmp_std_error_code.d \
./gmp_src_mgr/gmp_src/gmp_std_port.d \
./gmp_src_mgr/gmp_src/gmp_tunable.d \
./gmp_src_mgr/gmp_src/ht16k33.d \
./gmp_src_mgr/gmp_src/peripheral_driver.d \
./gmp_src_mgr/gmp_src/sysconfig_adapter.d 

OBJS += \
./gmp_src_mgr/gmp_src/PCA9555.obj \
./gmp_src_mgr/gmp_src/crc16.obj \
./gmp_src_mgr/gmp_src/ctl_adv_back_stepping.obj \
./gmp_src_mgr/gmp_src/ctl_adv_flc.obj \
./gmp_src_mgr/gmp_src/ctl_adv_flpid.obj \
./gmp_src_mgr/gmp_src/ctl_adv_ilc.obj \
./gmp_src_mgr/gmp_src/ctl_adv_imc.obj \
./gmp_src_mgr/gmp_src/ctl_adv_lms.obj \
./gmp_src_mgr/gmp_src/ctl_adv_lut_pair.obj \
./gmp_src_mgr/gmp_src/ctl_adv_mrac.obj \
./gmp_src_mgr/gmp_src/ctl_adv_rc.obj \
./gmp_src_mgr/gmp_src/ctl_adv_sinc_interpolator.obj \
./gmp_src_mgr/gmp_src/ctl_adv_smc.obj \
./gmp_src_mgr/gmp_src/ctl_adv_surf_search.obj \
./gmp_src_mgr/gmp_src/ctl_cia402_callback_fn.obj \
./gmp_src_mgr/gmp_src/ctl_cia402_state_machine.obj \
./gmp_src_mgr/gmp_src/ctl_component_interface.obj \
./gmp_src_mgr/gmp_src/ctl_continuous_pi.obj \
./gmp_src_mgr/gmp_src/ctl_continuous_pid.obj \
./gmp_src_mgr/gmp_src/ctl_continuous_pid_aw.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_biquad_filter.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_df.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_filter.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_lead_lag.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_pid.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_pole_zero.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_pr.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_sg.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_sogi.obj \
./gmp_src_mgr/gmp_src/ctl_discrete_track_pid.obj \
./gmp_src_mgr/gmp_src/ctl_disrete_fir.obj \
./gmp_src_mgr/gmp_src/ctl_divider.obj \
./gmp_src_mgr/gmp_src/ctl_dp_basic.obj \
./gmp_src_mgr/gmp_src/ctl_hysteresis_controller.obj \
./gmp_src_mgr/gmp_src/ctl_if_pwm_h.obj \
./gmp_src_mgr/gmp_src/ctl_if_pwm_npc.obj \
./gmp_src_mgr/gmp_src/ctl_if_pwm_spwm.obj \
./gmp_src_mgr/gmp_src/ctl_internal_ladrc1.obj \
./gmp_src_mgr/gmp_src/ctl_internal_ladrc2.obj \
./gmp_src_mgr/gmp_src/ctl_itoc_protection.obj \
./gmp_src_mgr/gmp_src/ctl_mc_acim_consultant.obj \
./gmp_src_mgr/gmp_src/ctl_mc_acim_fo.obj \
./gmp_src_mgr/gmp_src/ctl_mc_acim_pos_calc.obj \
./gmp_src_mgr/gmp_src/ctl_mc_acim_smo.obj \
./gmp_src_mgr/gmp_src/ctl_mc_ato_pll.obj \
./gmp_src_mgr/gmp_src/ctl_mc_basic_mech_ctrl.obj \
./gmp_src_mgr/gmp_src/ctl_mc_bldc_hall.obj \
./gmp_src_mgr/gmp_src/ctl_mc_bldc_zcd_obs.obj \
./gmp_src_mgr/gmp_src/ctl_mc_dtc_svm_core.obj \
./gmp_src_mgr/gmp_src/ctl_mc_encoder.obj \
./gmp_src_mgr/gmp_src/ctl_mc_encoder_switcher.obj \
./gmp_src_mgr/gmp_src/ctl_mc_foc_core.obj \
./gmp_src_mgr/gmp_src/ctl_mc_imfoc_core.obj \
./gmp_src_mgr/gmp_src/ctl_mc_inverter_consultant.obj \
./gmp_src_mgr/gmp_src/ctl_mc_ipm_fw.obj \
./gmp_src_mgr/gmp_src/ctl_mc_ladrc_pos_ctrl.obj \
./gmp_src_mgr/gmp_src/ctl_mc_ladrc_spd_ctrl.obj \
./gmp_src_mgr/gmp_src/ctl_mc_lut_fw.obj \
./gmp_src_mgr/gmp_src/ctl_mc_mech_consultant.obj \
./gmp_src_mgr/gmp_src/ctl_mc_mit_mech_ctrl.obj \
./gmp_src_mgr/gmp_src/ctl_mc_mtr_protection.obj \
./gmp_src_mgr/gmp_src/ctl_mc_mtr_vf_generator.obj \
./gmp_src_mgr/gmp_src/ctl_mc_nameplate_consultant.obj \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_consultant.obj \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_dbptc.obj \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_esmo.obj \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_fo.obj \
./gmp_src_mgr/gmp_src/ctl_mc_pmsm_hfi.obj \
./gmp_src_mgr/gmp_src/ctl_mc_pu_consultant.obj \
./gmp_src_mgr/gmp_src/ctl_mc_s_curve_traj.obj \
./gmp_src_mgr/gmp_src/ctl_mc_smc_mech_ctrl.obj \
./gmp_src_mgr/gmp_src/ctl_mc_sogi_traj.obj \
./gmp_src_mgr/gmp_src/ctl_mc_spm_fw.obj \
./gmp_src_mgr/gmp_src/ctl_mc_trapezoudal_traj.obj \
./gmp_src_mgr/gmp_src/ctl_nano.obj \
./gmp_src_mgr/gmp_src/ctl_protection.obj \
./gmp_src_mgr/gmp_src/ctl_sag_swell.obj \
./gmp_src_mgr/gmp_src/ctl_saturation.obj \
./gmp_src_mgr/gmp_src/ctl_slope_limiter.obj \
./gmp_src_mgr/gmp_src/ctl_sogi.obj \
./gmp_src_mgr/gmp_src/ctl_track_pid.obj \
./gmp_src_mgr/gmp_src/gmp_at_device.obj \
./gmp_src_mgr/gmp_src/gmp_datalink.obj \
./gmp_src_mgr/gmp_src/gmp_dev_util.obj \
./gmp_src_mgr/gmp_src/gmp_mem_presp.obj \
./gmp_src_mgr/gmp_src/gmp_mm_block_memory.obj \
./gmp_src_mgr/gmp_src/gmp_pil_core.obj \
./gmp_src_mgr/gmp_src/gmp_process_mgr.obj \
./gmp_src_mgr/gmp_src/gmp_std_error_code.obj \
./gmp_src_mgr/gmp_src/gmp_std_port.obj \
./gmp_src_mgr/gmp_src/gmp_tunable.obj \
./gmp_src_mgr/gmp_src/ht16k33.obj \
./gmp_src_mgr/gmp_src/peripheral_driver.obj \
./gmp_src_mgr/gmp_src/sysconfig_adapter.obj 

OBJS__QUOTED += \
"gmp_src_mgr\gmp_src\PCA9555.obj" \
"gmp_src_mgr\gmp_src\crc16.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_back_stepping.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_flc.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_flpid.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_ilc.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_imc.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_lms.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_lut_pair.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_mrac.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_rc.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_sinc_interpolator.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_smc.obj" \
"gmp_src_mgr\gmp_src\ctl_adv_surf_search.obj" \
"gmp_src_mgr\gmp_src\ctl_cia402_callback_fn.obj" \
"gmp_src_mgr\gmp_src\ctl_cia402_state_machine.obj" \
"gmp_src_mgr\gmp_src\ctl_component_interface.obj" \
"gmp_src_mgr\gmp_src\ctl_continuous_pi.obj" \
"gmp_src_mgr\gmp_src\ctl_continuous_pid.obj" \
"gmp_src_mgr\gmp_src\ctl_continuous_pid_aw.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_biquad_filter.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_df.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_filter.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_lead_lag.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_pid.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_pole_zero.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_pr.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_sg.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_sogi.obj" \
"gmp_src_mgr\gmp_src\ctl_discrete_track_pid.obj" \
"gmp_src_mgr\gmp_src\ctl_disrete_fir.obj" \
"gmp_src_mgr\gmp_src\ctl_divider.obj" \
"gmp_src_mgr\gmp_src\ctl_dp_basic.obj" \
"gmp_src_mgr\gmp_src\ctl_hysteresis_controller.obj" \
"gmp_src_mgr\gmp_src\ctl_if_pwm_h.obj" \
"gmp_src_mgr\gmp_src\ctl_if_pwm_npc.obj" \
"gmp_src_mgr\gmp_src\ctl_if_pwm_spwm.obj" \
"gmp_src_mgr\gmp_src\ctl_internal_ladrc1.obj" \
"gmp_src_mgr\gmp_src\ctl_internal_ladrc2.obj" \
"gmp_src_mgr\gmp_src\ctl_itoc_protection.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_consultant.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_fo.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_pos_calc.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_smo.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_ato_pll.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_basic_mech_ctrl.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_bldc_hall.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_bldc_zcd_obs.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_dtc_svm_core.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_encoder.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_encoder_switcher.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_foc_core.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_imfoc_core.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_inverter_consultant.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_ipm_fw.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_ladrc_pos_ctrl.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_ladrc_spd_ctrl.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_lut_fw.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_mech_consultant.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_mit_mech_ctrl.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_mtr_protection.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_mtr_vf_generator.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_nameplate_consultant.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_consultant.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_dbptc.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_esmo.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_fo.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_hfi.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_pu_consultant.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_s_curve_traj.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_smc_mech_ctrl.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_sogi_traj.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_spm_fw.obj" \
"gmp_src_mgr\gmp_src\ctl_mc_trapezoudal_traj.obj" \
"gmp_src_mgr\gmp_src\ctl_nano.obj" \
"gmp_src_mgr\gmp_src\ctl_protection.obj" \
"gmp_src_mgr\gmp_src\ctl_sag_swell.obj" \
"gmp_src_mgr\gmp_src\ctl_saturation.obj" \
"gmp_src_mgr\gmp_src\ctl_slope_limiter.obj" \
"gmp_src_mgr\gmp_src\ctl_sogi.obj" \
"gmp_src_mgr\gmp_src\ctl_track_pid.obj" \
"gmp_src_mgr\gmp_src\gmp_at_device.obj" \
"gmp_src_mgr\gmp_src\gmp_datalink.obj" \
"gmp_src_mgr\gmp_src\gmp_dev_util.obj" \
"gmp_src_mgr\gmp_src\gmp_mem_presp.obj" \
"gmp_src_mgr\gmp_src\gmp_mm_block_memory.obj" \
"gmp_src_mgr\gmp_src\gmp_pil_core.obj" \
"gmp_src_mgr\gmp_src\gmp_process_mgr.obj" \
"gmp_src_mgr\gmp_src\gmp_std_error_code.obj" \
"gmp_src_mgr\gmp_src\gmp_std_port.obj" \
"gmp_src_mgr\gmp_src\gmp_tunable.obj" \
"gmp_src_mgr\gmp_src\ht16k33.obj" \
"gmp_src_mgr\gmp_src\peripheral_driver.obj" \
"gmp_src_mgr\gmp_src\sysconfig_adapter.obj" 

C_DEPS__QUOTED += \
"gmp_src_mgr\gmp_src\PCA9555.d" \
"gmp_src_mgr\gmp_src\crc16.d" \
"gmp_src_mgr\gmp_src\ctl_adv_back_stepping.d" \
"gmp_src_mgr\gmp_src\ctl_adv_flc.d" \
"gmp_src_mgr\gmp_src\ctl_adv_flpid.d" \
"gmp_src_mgr\gmp_src\ctl_adv_ilc.d" \
"gmp_src_mgr\gmp_src\ctl_adv_imc.d" \
"gmp_src_mgr\gmp_src\ctl_adv_lms.d" \
"gmp_src_mgr\gmp_src\ctl_adv_lut_pair.d" \
"gmp_src_mgr\gmp_src\ctl_adv_mrac.d" \
"gmp_src_mgr\gmp_src\ctl_adv_rc.d" \
"gmp_src_mgr\gmp_src\ctl_adv_sinc_interpolator.d" \
"gmp_src_mgr\gmp_src\ctl_adv_smc.d" \
"gmp_src_mgr\gmp_src\ctl_adv_surf_search.d" \
"gmp_src_mgr\gmp_src\ctl_cia402_callback_fn.d" \
"gmp_src_mgr\gmp_src\ctl_cia402_state_machine.d" \
"gmp_src_mgr\gmp_src\ctl_component_interface.d" \
"gmp_src_mgr\gmp_src\ctl_continuous_pi.d" \
"gmp_src_mgr\gmp_src\ctl_continuous_pid.d" \
"gmp_src_mgr\gmp_src\ctl_continuous_pid_aw.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_biquad_filter.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_df.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_filter.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_lead_lag.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_pid.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_pole_zero.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_pr.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_sg.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_sogi.d" \
"gmp_src_mgr\gmp_src\ctl_discrete_track_pid.d" \
"gmp_src_mgr\gmp_src\ctl_disrete_fir.d" \
"gmp_src_mgr\gmp_src\ctl_divider.d" \
"gmp_src_mgr\gmp_src\ctl_dp_basic.d" \
"gmp_src_mgr\gmp_src\ctl_hysteresis_controller.d" \
"gmp_src_mgr\gmp_src\ctl_if_pwm_h.d" \
"gmp_src_mgr\gmp_src\ctl_if_pwm_npc.d" \
"gmp_src_mgr\gmp_src\ctl_if_pwm_spwm.d" \
"gmp_src_mgr\gmp_src\ctl_internal_ladrc1.d" \
"gmp_src_mgr\gmp_src\ctl_internal_ladrc2.d" \
"gmp_src_mgr\gmp_src\ctl_itoc_protection.d" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_consultant.d" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_fo.d" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_pos_calc.d" \
"gmp_src_mgr\gmp_src\ctl_mc_acim_smo.d" \
"gmp_src_mgr\gmp_src\ctl_mc_ato_pll.d" \
"gmp_src_mgr\gmp_src\ctl_mc_basic_mech_ctrl.d" \
"gmp_src_mgr\gmp_src\ctl_mc_bldc_hall.d" \
"gmp_src_mgr\gmp_src\ctl_mc_bldc_zcd_obs.d" \
"gmp_src_mgr\gmp_src\ctl_mc_dtc_svm_core.d" \
"gmp_src_mgr\gmp_src\ctl_mc_encoder.d" \
"gmp_src_mgr\gmp_src\ctl_mc_encoder_switcher.d" \
"gmp_src_mgr\gmp_src\ctl_mc_foc_core.d" \
"gmp_src_mgr\gmp_src\ctl_mc_imfoc_core.d" \
"gmp_src_mgr\gmp_src\ctl_mc_inverter_consultant.d" \
"gmp_src_mgr\gmp_src\ctl_mc_ipm_fw.d" \
"gmp_src_mgr\gmp_src\ctl_mc_ladrc_pos_ctrl.d" \
"gmp_src_mgr\gmp_src\ctl_mc_ladrc_spd_ctrl.d" \
"gmp_src_mgr\gmp_src\ctl_mc_lut_fw.d" \
"gmp_src_mgr\gmp_src\ctl_mc_mech_consultant.d" \
"gmp_src_mgr\gmp_src\ctl_mc_mit_mech_ctrl.d" \
"gmp_src_mgr\gmp_src\ctl_mc_mtr_protection.d" \
"gmp_src_mgr\gmp_src\ctl_mc_mtr_vf_generator.d" \
"gmp_src_mgr\gmp_src\ctl_mc_nameplate_consultant.d" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_consultant.d" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_dbptc.d" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_esmo.d" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_fo.d" \
"gmp_src_mgr\gmp_src\ctl_mc_pmsm_hfi.d" \
"gmp_src_mgr\gmp_src\ctl_mc_pu_consultant.d" \
"gmp_src_mgr\gmp_src\ctl_mc_s_curve_traj.d" \
"gmp_src_mgr\gmp_src\ctl_mc_smc_mech_ctrl.d" \
"gmp_src_mgr\gmp_src\ctl_mc_sogi_traj.d" \
"gmp_src_mgr\gmp_src\ctl_mc_spm_fw.d" \
"gmp_src_mgr\gmp_src\ctl_mc_trapezoudal_traj.d" \
"gmp_src_mgr\gmp_src\ctl_nano.d" \
"gmp_src_mgr\gmp_src\ctl_protection.d" \
"gmp_src_mgr\gmp_src\ctl_sag_swell.d" \
"gmp_src_mgr\gmp_src\ctl_saturation.d" \
"gmp_src_mgr\gmp_src\ctl_slope_limiter.d" \
"gmp_src_mgr\gmp_src\ctl_sogi.d" \
"gmp_src_mgr\gmp_src\ctl_track_pid.d" \
"gmp_src_mgr\gmp_src\gmp_at_device.d" \
"gmp_src_mgr\gmp_src\gmp_datalink.d" \
"gmp_src_mgr\gmp_src\gmp_dev_util.d" \
"gmp_src_mgr\gmp_src\gmp_mem_presp.d" \
"gmp_src_mgr\gmp_src\gmp_mm_block_memory.d" \
"gmp_src_mgr\gmp_src\gmp_pil_core.d" \
"gmp_src_mgr\gmp_src\gmp_process_mgr.d" \
"gmp_src_mgr\gmp_src\gmp_std_error_code.d" \
"gmp_src_mgr\gmp_src\gmp_std_port.d" \
"gmp_src_mgr\gmp_src\gmp_tunable.d" \
"gmp_src_mgr\gmp_src\ht16k33.d" \
"gmp_src_mgr\gmp_src\peripheral_driver.d" \
"gmp_src_mgr\gmp_src\sysconfig_adapter.d" 

C_SRCS__QUOTED += \
"../gmp_src_mgr/gmp_src/PCA9555.c" \
"../gmp_src_mgr/gmp_src/crc16.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_back_stepping.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_flc.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_flpid.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_ilc.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_imc.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_lms.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_lut_pair.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_mrac.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_rc.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_sinc_interpolator.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_smc.c" \
"../gmp_src_mgr/gmp_src/ctl_adv_surf_search.c" \
"../gmp_src_mgr/gmp_src/ctl_cia402_callback_fn.c" \
"../gmp_src_mgr/gmp_src/ctl_cia402_state_machine.c" \
"../gmp_src_mgr/gmp_src/ctl_component_interface.c" \
"../gmp_src_mgr/gmp_src/ctl_continuous_pi.c" \
"../gmp_src_mgr/gmp_src/ctl_continuous_pid.c" \
"../gmp_src_mgr/gmp_src/ctl_continuous_pid_aw.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_biquad_filter.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_df.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_filter.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_lead_lag.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_pid.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_pole_zero.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_pr.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_sg.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_sogi.c" \
"../gmp_src_mgr/gmp_src/ctl_discrete_track_pid.c" \
"../gmp_src_mgr/gmp_src/ctl_disrete_fir.c" \
"../gmp_src_mgr/gmp_src/ctl_divider.c" \
"../gmp_src_mgr/gmp_src/ctl_dp_basic.c" \
"../gmp_src_mgr/gmp_src/ctl_hysteresis_controller.c" \
"../gmp_src_mgr/gmp_src/ctl_if_pwm_h.c" \
"../gmp_src_mgr/gmp_src/ctl_if_pwm_npc.c" \
"../gmp_src_mgr/gmp_src/ctl_if_pwm_spwm.c" \
"../gmp_src_mgr/gmp_src/ctl_internal_ladrc1.c" \
"../gmp_src_mgr/gmp_src/ctl_internal_ladrc2.c" \
"../gmp_src_mgr/gmp_src/ctl_itoc_protection.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_acim_consultant.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_acim_fo.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_acim_pos_calc.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_acim_smo.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_ato_pll.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_basic_mech_ctrl.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_bldc_hall.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_bldc_zcd_obs.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_dtc_svm_core.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_encoder.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_encoder_switcher.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_foc_core.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_imfoc_core.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_inverter_consultant.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_ipm_fw.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_ladrc_pos_ctrl.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_ladrc_spd_ctrl.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_lut_fw.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_mech_consultant.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_mit_mech_ctrl.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_mtr_protection.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_mtr_vf_generator.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_nameplate_consultant.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_pmsm_consultant.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_pmsm_dbptc.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_pmsm_esmo.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_pmsm_fo.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_pmsm_hfi.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_pu_consultant.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_s_curve_traj.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_smc_mech_ctrl.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_sogi_traj.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_spm_fw.c" \
"../gmp_src_mgr/gmp_src/ctl_mc_trapezoudal_traj.c" \
"../gmp_src_mgr/gmp_src/ctl_nano.c" \
"../gmp_src_mgr/gmp_src/ctl_protection.c" \
"../gmp_src_mgr/gmp_src/ctl_sag_swell.c" \
"../gmp_src_mgr/gmp_src/ctl_saturation.c" \
"../gmp_src_mgr/gmp_src/ctl_slope_limiter.c" \
"../gmp_src_mgr/gmp_src/ctl_sogi.c" \
"../gmp_src_mgr/gmp_src/ctl_track_pid.c" \
"../gmp_src_mgr/gmp_src/gmp_at_device.c" \
"../gmp_src_mgr/gmp_src/gmp_datalink.c" \
"../gmp_src_mgr/gmp_src/gmp_dev_util.c" \
"../gmp_src_mgr/gmp_src/gmp_mem_presp.c" \
"../gmp_src_mgr/gmp_src/gmp_mm_block_memory.c" \
"../gmp_src_mgr/gmp_src/gmp_pil_core.c" \
"../gmp_src_mgr/gmp_src/gmp_process_mgr.c" \
"../gmp_src_mgr/gmp_src/gmp_std_error_code.c" \
"../gmp_src_mgr/gmp_src/gmp_std_port.c" \
"../gmp_src_mgr/gmp_src/gmp_tunable.c" \
"../gmp_src_mgr/gmp_src/ht16k33.c" \
"../gmp_src_mgr/gmp_src/peripheral_driver.c" \
"../gmp_src_mgr/gmp_src/sysconfig_adapter.c" 


