/**
 * @file sysconfig_adapter.c
 * @author Javnson (javnson@zju.edu.cn)
 * @brief
 * @version 0.1
 * @date 2025-01-18
 *
 * @copyright Copyright GMP(c) 2024
 *
 */

// This file provide a set of function that CSP must defined.

#include <gmp_core.h>
#include <stdio.h>
#include <string.h>

#include <c28x_peripheral_driver.h>
#include <ctl/component/intrinsic/basic/divider.h>

// System Tick
time_gt DSPC2000_SystemTick = 0;

// User should invoke this function to get time (system tick).
time_gt gmp_base_get_system_tick(void)
{
    return DSPC2000_SystemTick;
}

// No divider default
#ifndef DSP_C2000_DSP_TIME_DIV
#define DSP_C2000_DSP_TIME_DIV ((10))
#endif // DSP_C2000_DSP_TIME_DIV

ctl_divider_t sys_tick_div;

// This function should be called in order to get system tick.
void gmp_step_system_tick(void)
{
    if (ctl_step_divider(&sys_tick_div))
        DSPC2000_SystemTick += 1;
}

// This function may be called and used to initialize all the peripheral.
void gmp_csp_startup(void)
{

    // #ifndef _C2000_CSP_DISBALE_LINKER_CMD_TOOL_
    //     //
    //     // This function is generated by SysConfig Software
    //     //  You may switch on LINKER COMMAND FILE CONFIG - CMD
    //     //
    //     CMD_init();
    // #endif // _C2000_CSP_DISBALE_LINKER_CMD_TOOL_

    //
    // This function is generated by SysConfig Software
    // You may switch on Software - Device Support.
    // If you don't setup this option, you should implement
    // the following routine yourself before invoke GMP Entry.
    //
#ifndef _C2000_CSP_DISABLE_DEVICE_SUPPORT_

    //
    // Function to initialize the device.
    //
    Device_init();

    //
    // Turn on all peripherals
    //
    Device_enableAllPeripherals();

    //
    // Function to disable pin locks and enable pullups on GPIOs.
    //
    Device_initGPIO();

    //
    // Initializes the PIE control registers by setting
    // them to a known state.
    //
    Interrupt_initModule();
    Interrupt_initVectorTable();

#endif // _C2000_DSP_DISABLE_DEVICE_SUPPORT_

    //
    // Disable sync(Freeze clock to PWM as well)
    //
    SysCtl_disablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);

    //
    // This function is generated by SysConfig Software.
    //
    Board_init();

    //
    // Enable sync and clock to PWM
    //
    SysCtl_enablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);

    //
    // This function is generated by SysConfig Software.
    // If you use some library
    //
#ifndef _C2000_CSP_DISABLE_C2000WARE_LIBRARY_
    C2000Ware_libraries_init();
#endif // _C2000_CSP_DISABLE_C2000WARE_LIBRARY_

    //
    // Run ADC offset calibration
    //
    // Init_runAdcZeroCalibration();

    // Init divider object @sys_tick_div for System tick
    ctl_init_divider(&sys_tick_div, DSP_C2000_DSP_TIME_DIV);

    // clear System tick counter
    DSPC2000_SystemTick = 0;
}

void gmp_csp_loop()
{
}

void gmp_csp_post_process()
{
    //
    // Enable Global Interrupts (INTM) and realtime interrupt (DGBM)
    //
    EINT;
    ERTM;
}

uart_halt debug_uart;

// implement the gmp_debug_print routine.
size_gt gmp_base_print_c28xsyscfg(const char* p_fmt, ...)
{
    // if no one was specified to output, just ignore the request.
    if (debug_uart == NULL)
    {
        return 0;
    }

    // size_gt size = (size_gt)strlen(p_fmt);

    static data_gt str[GMP_BASE_PRINT_CHAR_EXT];
    memset(str, 0, GMP_BASE_PRINT_CHAR_EXT);

    va_list vArgs;
    va_start(vArgs, p_fmt);
    vsprintf((char*)str, (char const*)p_fmt, vArgs);
    va_end(vArgs);

    size_gt length = (size_gt)strlen((char*)str);

    gmp_hal_uart_write(debug_uart, str, length, 10);

    return length;
}

// main function, user no need for repeated definition.
void main()
{
    gmp_base_entry();
}
